[package]
authors = ["Kristoffer Ström <kristoffer@rymdkoloni.se>"]
name = "diskarray"
version = "0.1.0"

[dependencies]
memmap = "0.5.2"
oncemutex = "0.1.1"
parking_lot = "0.4.8"
seahash = "3.0"

[dev-dependencies]
tempdir = "0.3.5"
